name: jsqpro automatic

on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: checkout source code
      - name: Get Tag
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-env name=BRANCH::$branch
      - run: echo ${{ env.BRANCH }}
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      # - run: npm install
      # - run: npm test
      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
